export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// FONTS
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Container } from '@mui/material';


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Container maxWidth="sm">
        {children}
        </Container>
        </body>
    </html>
  )
}
